geometry_msgs/PoseStamped[]     plan
OrientationConstraint           orientation_constraint
---
bool                            result
---
float64                         dtg
bool                            blocked
bool                            frame_exists
